#! /bin/sh

# This script is RPM-specific
# It is run at the very end of an install/upgrade of the package
# It is NOT run on removal of the package

getent group paas-agent >/dev/null || groupadd -r paas-agent
getent passwd paas-agent >/dev/null || \
    useradd -r -M -g paas-agent -d /usr/share/paasinsight/agent -s /bin/sh \
    -c "PaasInsight Agent" paas-agent
/etc/init.d/paas-agent restart
exit 0
