#!/bin/sh
LINUX_DISTRIBUTION=$(grep -Eo "(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon|SUSE)" /etc/issue)

if [ -f "/etc/debian_version" ] || [ "$LINUX_DISTRIBUTION" == "Debian" ] || [ "$LINUX_DISTRIBUTION" == "Ubuntu" ]; then
    set -e

    if [ "$1" = purge ]; then
        echo "Deleting paas-agent user"
        deluser paas-agent --quiet
        echo "Deleting paas-agent group"
        getent group paas-agent >/dev/null && delgroup paas-agent --quiet || true
        rm -rf /opt/paas-agent
        rm -rf /var/log/paasinsight
        rm -rf /etc/paas-agent
        rm -rf /var/log/paasinsight
    fi
elif [ -f "/etc/redhat-release" ] || [ "$LINUX_DISTRIBUTION" == "RedHat" ] || [ "$LINUX_DISTRIBUTION" == "CentOS" ] || [ "$LINUX_DISTRIBUTION" == "openSUSE" ] || [ "$LINUX_DISTRIBUTION" == "Amazon" ] || [ "$LINUX_DISTRIBUTION" == "SUSE" ]; then
    case "$*" in
      0)
        # We're uninstalling.
        # We don't delete the paas-agent user/group (see https://fedoraproject.org/wiki/Packaging:UsersAndGroups#Allocation_Strategies)
        ;;
      1)
        # We're upgrading.
        ;;
      *)
        ;;
    esac
else
      echo "[ ${Red}FAILED ${RCol}]\tYour system is currently not supported by this script.";
      exit 1;
fi
exit 0
